import Head from 'next/head'
import {HomePage} from '@/src/components/home/home-page'
export default function Home({data}) {
  return (
    <div className="landPage">
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
      </Head>
      <HomePage data={data}/>
    </div>
    
  )
  
}
export async function getServerSideProps() {
  const {events_categories} = await import('@/data/data.json')
  return {
      props: {
          data: events_categories
      }
  }
}